# https://docs.docker.com/compose/compose-file/#external_links

version: '3'
services:
  project-managment-backend:
    container_name: project-managment-backend
    hostname: project-managment-backend
    image: pl.braintelligence:latest
    ports:
      - "8080:8080"
  prometheus:
    image: prom/prometheus:v2.1.0
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  mongo:
    image: mongo:3.2.4
    ports:
      - 27017:27017
    command: --smallfiles
  mongo-client:
    image: mongoclient/mongoclient
    ports:
      - 3030:3001
    environment:
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017
    links:
      - mongo
